### PR TITLE
added twine version

### PR DESCRIPTION
**Pull request by domdinicola**

### CODE REVIEW

**Comment by domdinicola** [comment]
@vgrem hope this help

**Comment by vgrem** [comment]
@domdinicola , unfortunately same error occurs

> Could not restore untracked files from stash entry
> PyPI upload failed.
> failed to deploy

**Comment by domdinicola** [comment]
looks like the change is not there
https://travis-ci.org/github/vgrem/Office365-REST-Python-Client/jobs/675475923/config

Il giorno mer 15 apr 2020 alle ore 18:24 Vadim Gremyachev <
notifications@github.com> ha scritto:

**Comment by vgrem** [comment]
[this one](https://travis-ci.org/github/vgrem/Office365-REST-Python-Client/builds/675496456/config) is the latest build

**Pull request merged**
