### PR TITLE
"add list item" example

### PR DESCRIPTION
**Pull request by beliaev-maksim**

### CODE REVIEW

**Comment by beliaev-maksim** [comment]
@vgrem 
actually I think will be good also to add an example how to delete list Item

is this functionality already implemented?
if yes, can you please give a hint where to look and I will add an example

**Comment by vgrem** [comment]
@beliaev-maksim, delete operation for `ListItem` is supported as well,  the examples could be found [here](https://github.com/vgrem/Office365-REST-Python-Client/blob/master/tests/sharepoint/test_listItem.py) 

A few suggestions regarding the change, maybe more beneficial would be: 

- to create examples for CRUD operations, the similar way how it is demonstrated in  [official  doc](https://docs.microsoft.com/en-us/previous-versions/office/developer/sharepoint-2010/ee539976(v=office.14))    
 
- and provide _as generic examples as possible_ (e.g. without any custom fields involved) , for instance demonstrate it against `Tasks` list or `Documents` library

**Comment by beliaev-maksim** [comment]
@vgrem 
agreed, I changed all names to generic as possible and now we have add/update/delete examples

also I added new function to the list collection that will allow to recycle all items based on filter dictionary. I also added example for that one. Could be useful for bulk recycle based on some criteria

**Comment by vgrem** [comment]
Thanks! 👍  Will review and get back later

**Comment by vgrem** [comment]
@beliaev-maksim thanks!

A few suggestions:

- since you are referring to out-of-the-box `Tasks`  lets utilize _standard_ properties instead of _custom_ ones (`build_date` and etc.)  I still believe it is better to stick to examples provided in [official doc](https://docs.microsoft.com/en-us/previous-versions/office/developer/sharepoint-2010/ee539976(v=office.14)  Assume a person without any previous experience would like give it a try, apparently running provided examples requires some extra effort which is not desirable for the case of examples.. 

- `recycle_item_by_property` looks specific, propose to abandon it. Let's try to refrain from methods that don't belong to the library (unless they bring considerable value). Could elaborate if needed but the general idea the library to be compliant with another SDKs in terms of API.

**Comment by beliaev-maksim** [comment]
@vgrem 
in original API you can query list items specifying query. However this is not really "pythonic". In this case using dictionary it will go really easy and smooth to make bulk clean up of the list. Try one of examples, hope syntax is intuitive

names or columns will change

**Comment by vgrem** [comment]
@beliaev-maksim 
  
I propose to stick to standard operations for list item (https://docs.microsoft.com/en-us/previous-versions/office/developer/sharepoint-2010/ee539976(v=office.14))), it is intended to be how-to examples, right:

- create list item
- get list item (by id)
- update list item
- delete list item

You could refer [How to: Create, Update, and Delete List Items](https://docs.microsoft.com/en-us/previous-versions/office/developer/sharepoint-2010/ee539976(v=office.14)) for a details


Speaking of `recycle_item_by_property` would like to raise a few concerns:

1) loading whole collection of items should to be avoided at all cost, not only from perspective point of view, to perform operations in a batch mode (recycle in your case)  there are a way better ways available (at least two which I'm aware of)

```
            if not self.items:
                self.context.load(items)
                self.context.execute_query()
```

2) to make it more pythonic you say, good idea.  Like i said about avoiding introducing custom methods on top of existing API, may be instead consider some generic solution with filtering/querying which utilizes the language features and which could be transformed into either underlying OData request/Caml query

**Comment by beliaev-maksim** [comment]
@vgrem 
ok, this example I can rework

however from practical point of view would be really good to provide example where user can

1. delete items
2. recycle items
based on some criteria. When some values are matching some filter.

what would be the best approach?
this we can include in another example file 


also when I see example [read_large_list](https://github.com/vgrem/Office365-REST-Python-Client/blob/master/examples/sharepoint/lists_and_items/read_large_list.py) it looks like the whole list is also loaded in this case. 
Can we load and perform actions on chunks of list items?

**Comment by beliaev-maksim** [comment]
@vgrem 
I fixed examples, removed function and squashed all commits

please check and merge.

I also found a small bug in another example, fixed within commit

**Comment by beliaev-maksim** [comment]
@vgrem 
I see you fixed download example, I removed it from PR

**Comment by beliaev-maksim** [comment]
@vgrem
Is there any issue?

**Comment by vgrem** [comment]
Hey, thanks!

A few suggestions:

a) since a _Create_ operation is demonstrated against out-of-the-box `Tasks `list,  maybe it would be more beneficial to demonstrate how to set _Task field values_ (preferably different field types):     

target_list.add_item({
    "Title": "my_title",  # note, you can rename columns after they created but have to use name of initial column
    "version": "1",
    ^^^^^^^^
    "Date": "2020-11-17",
    ^^^^^^^^^^^^^^ 
    "Active": False  # for Yes/No items you have to provide bool value^
    ^^^^^^^^^^
})

[SharePoint list item tasks](https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/complete-basic-operations-using-sharepoint-client-library-code#sharepoint-list-item-tasks) could be used as a starting point

b) prefer a standard terminology, so instead of saying  _update Item property_  lets phrase it like this: _update list item_  You could refer [Microsoft 365 Glossary ](https://docs.microsoft.com/en-us/microsoft-365/community/glossary) for a terminology
 

c) avoid hard coded values, e.g. `item_to_update = target_list.get_item_by_id(54)`



p.s. Sorry for the late reply.

**Comment by beliaev-maksim** [comment]
Hi @vgrem ,

actually I checked on my SharePoint Online and I do not see any additional field types. All other field types are just numbers or strings. Or is there some tricky one?
Also I am not targeting Tasks but general sharepoint list. There are multiple use cases for lists

regarding hard coding, Microsoft docs does it, here is cut from help:
```
// Assume there is a list item with ID=1.  
ListItem listItem = announcementsList.GetItemById(1);
```

**Comment by beliaev-maksim** [comment]
hi @vgrem 
what do you think about this example file for lists (I do not target here any task list, just general sharepoint list)?

**Comment by vgrem** [comment]
Hey, thanks for the update, abit forgot what this change was about, will review and get back.

**Comment by vgrem** [comment]
Thanks, lets (finally) include it into the next release but with a few changes. Since create and update operations are pretty much covered nowadays in examples section, let's keep only recycle and permanent delete examples

**Pull request merged**
