### PR TITLE
Added support for adding attachment on list item

### PR DESCRIPTION
**Pull request by Toilal**
Do not merge, this is still a work in progress.

### CODE REVIEW

**Comment by Toilal** [comment]
Seems there are some issues related to the Sharepoint testing server, but one build has worked properly : https://travis-ci.org/vgrem/Office365-REST-Python-Client/jobs/291962094

I think it's ready to merge.

**Comment by Toilal** [comment]
After this beeing merge, could you perform a release on pipy ?

**Comment by Toilal** [comment]
Problem with TravisCI tests is that mutiple jobs are running against the same SharePoint instance, causing some race condition problems.

**Comment by Toilal** [comment]
I think tests are now ok, let's wait travis CI build on master branch

**Comment by Toilal** [comment]
Tests are OK : https://travis-ci.org/vgrem/Office365-REST-Python-Client For some reason, it failed to git clone for 3.6, maybe you could restart the jobs ?

**Comment by vgrem** [comment]
Greetings,

you are right regarding race condition.  Tests are getting executed against a single site tenant per different Python runtimes.  Some objects are shared across the tests.

**Comment by vgrem** [comment]
Surprisingly the following error occurs while trying to run job for Python 3.6

> The command "eval git fetch origin +refs/pull/50/merge: 

Not sure what could cause it so far..

**Comment by Toilal** [comment]
If you login to travis CI (https://travis-ci.org/vgrem/Office365-REST-Python-Client) with your github account, you can restart the build. see https://stackoverflow.com/questions/17606874/trigger-a-travis-ci-rebuild-without-pushing-a-commit

**Comment by kgadek** [comment]
> After this beeing merge, could you perform a release on pipy ?

Sure. I'll review all changes since last release and will do the upload this evening.

**Pull request merged**
