### PR TITLE
added possibility to create folder tree + example + fix

### PR DESCRIPTION
**Pull request by beliaev-maksim**
allow user to specify leading slash in url for get_folder_by_server_relative_url

added example how to add folder

### CODE REVIEW

**Comment by beliaev-maksim** [comment]
@vgrem 
Hi, looks like an issue in Travis config: office365_python_sdk_securevars is missed

do not think my changes affected

**Comment by vgrem** [comment]
@beliaev-maksim, nothing to be worried about,  `office365_python_sdk_securevars` environment variables seems only visible per master branch but not per branch, meaning something is not configured properly in Travis CI :)  

Regarding the change, thanks! `create_folder_tree` might be a way more useful in some cases over regular `add ` method.

Although would prefer one minor change, how about `ensure_folder` name instead,  more concise from naming convection perspective?

**Comment by beliaev-maksim** [comment]
@vgrem 
ah, OK, usually I am scared by All Checks have failed :D


I was also thinking about ensure name.
what is about `ensure_relative_path` or `ensure_folder_tree`  or maybe `ensure_relative_url`? Somehow to point from the name that this will validate and create multiple folders, tree in this case

**Comment by vgrem** [comment]
@beliaev-maksim  

>  `ensure_relative_path ` and `ensure_relative_url`

sounds abit unclear for a novice what this is about.

[Our competitors](https://docs.microsoft.com/en-us/dotnet/api/microsoft.sharepoint.client.filefolderextensions.ensurefolderpath?view=sharepoint-pnpcoreol-3.2.1810) comes to the rescue, how about  `ensure_folder_path(path)`  ?

_The benefit is a naming consistency across different SDK, for those who will decide to migrate from C# SDK probably will appreciate it ;)_

**Comment by beliaev-maksim** [comment]
@vgrem,
yes, good idea, will do a change!

fully agree, consistency is important

**Pull request merged**
