### PR TITLE
Conditionally import `ParamSpec` from `typing_extensions`

### PR DESCRIPTION
**Pull request by thaiphv**
Attempt to fix https://github.com/vgrem/Office365-REST-Python-Client/issues/756 and https://github.com/vgrem/Office365-REST-Python-Client/issues/755

### CODE REVIEW

**Comment by vgrem** [comment]
Thanks for catching this and providing the solution!

**Comment by thaiphv** [comment]
Hi @vgrem, thanks for approving the PR. Do you think you can make a patch release soon?

**Comment by vgrem** [comment]
@thaiphv, [`2.5.1 `version](https://github.com/vgrem/Office365-REST-Python-Client/releases) has been released

**Comment by ignaciocabeza** [comment]
thanks @thaiphv @vgrem!

**Pull request merged**
